"""Agre dos columnas nuevas lastname y username

Revision ID: 1e4f5fe11979
Revises: 
Create Date: 2025-04-26 15:43:33.124120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e4f5fe11979'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastName', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('username')
        batch_op.drop_column('lastName')

    # ### end Alembic commands ###
