"""Agregue dos columnas nuevas

Revision ID: 574adcae2645
Revises: 1e4f5fe11979
Create Date: 2025-05-02 13:11:55.853123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '574adcae2645'
down_revision = '1e4f5fe11979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_perfil', sa.String(length=10000), nullable=True))
        batch_op.add_column(sa.Column('port_page', sa.String(length=10000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('port_page')
        batch_op.drop_column('photo_perfil')

    # ### end Alembic commands ###
