"""Elimine dos columnas

Revision ID: b4747f0362b0
Revises: 574adcae2645
Create Date: 2025-05-02 13:53:15.239783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4747f0362b0'
down_revision = '574adcae2645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('port_page')
        batch_op.drop_column('photo_perfil')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_perfil', sa.VARCHAR(length=10000), nullable=True))
        batch_op.add_column(sa.Column('port_page', sa.VARCHAR(length=10000), nullable=True))

    # ### end Alembic commands ###
